package com.example.demo.dao.pojo;

import java.util.Date;

public class Record {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.recordid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private String recordid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.userid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.payeename
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private String payeename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.payeeemail
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private String payeeemail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.money
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.createtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private Date createtime;

    private String createtimeStr;

    public String getCreatetimeStr() {
        return createtimeStr;
    }

    public void setCreatetimeStr(String createtimeStr) {
        this.createtimeStr = createtimeStr;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.status
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.repaytime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private Date repaytime;

    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column record.remindtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    private Date remindtime;


    private String remindtimeStr;

    public String getRemindtimeStr() {
        return remindtimeStr;
    }

    public void setRemindtimeStr(String remindtimeStr) {
        this.remindtimeStr = remindtimeStr;
    }

    private String repaytimeStr;

    public String getRepaytimeStr() {
        return repaytimeStr;
    }

    public void setRepaytimeStr(String repaytimeStr) {
        this.repaytimeStr = repaytimeStr;
    }

    private  Integer del;

    public Integer getDel() {
        return del;
    }

    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.recordid
     *
     * @return the value of record.recordid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public String getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.recordid
     *
     * @param recordid the value for record.recordid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setRecordid(String recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.userid
     *
     * @return the value of record.userid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.userid
     *
     * @param userid the value for record.userid
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.payeename
     *
     * @return the value of record.payeename
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public String getPayeename() {
        return payeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.payeename
     *
     * @param payeename the value for record.payeename
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setPayeename(String payeename) {
        this.payeename = payeename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.payeeemail
     *
     * @return the value of record.payeeemail
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public String getPayeeemail() {
        return payeeemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.payeeemail
     *
     * @param payeeemail the value for record.payeeemail
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setPayeeemail(String payeeemail) {
        this.payeeemail = payeeemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.money
     *
     * @return the value of record.money
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.money
     *
     * @param money the value for record.money
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.createtime
     *
     * @return the value of record.createtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.createtime
     *
     * @param createtime the value for record.createtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.status
     *
     * @return the value of record.status
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.status
     *
     * @param status the value for record.status
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.repaytime
     *
     * @return the value of record.repaytime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public Date getRepaytime() {
        return repaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.repaytime
     *
     * @param repaytime the value for record.repaytime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setRepaytime(Date repaytime) {
        this.repaytime = repaytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column record.remindtime
     *
     * @return the value of record.remindtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public Date getRemindtime() {
        return remindtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column record.remindtime
     *
     * @param remindtime the value for record.remindtime
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    public void setRemindtime(Date remindtime) {
        this.remindtime = remindtime;
    }
}