package com.example.demo.dao.mapper;

import com.example.demo.dao.pojo.User;
import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Apr 01 21:12:49 CST 2020
     */
    List<User> selectAll();


    User  selectAnyParams(User record);
}